### ISSUE TITLE
Unable to mock useAutosave hook since 0.4.0

### ISSUE THREAD

**Issue by ockam** [jollyjerr/react-autosave#16]
Just installed the 0.4.0 update (thanks for the quick update) and the useAutosave hook mock (jest-mock) I was using in my tests stopped working.

It fails with the error `Failed to get mock metadata: [...]/node_modules/react-autosave/dist/react-autosave.umd.js`.

I’m no test guru, so I don’t have a fix to suggest, but I continue trying to find a workaround on my end.

**Comment by jollyjerr** [comment]
Thank you for letting me know 👍🏼 Might be best to downgrade until I can get a fix.

**Comment by ockam** [comment]
Explicitly defining the mock does the trick:

`jest.mock('react-autosave', () => ({ useAutosave: jest.fn() }))`

**Comment by jollyjerr** [comment]
Nice! I will try to get it working again in the future anyway. What major version of jest are you using? 26, 27, or 28?

**Comment by ockam** [comment]
Jest 27.5.1 with React 17.0.2

**Comment by jollyjerr** [comment]
This should be fixed in 0.4.2
