### ISSUE TITLE
onSave is called if onSave changes. Can this be optional?

### ISSUE THREAD

**Issue by mspangl5** [jollyjerr/react-autosave#17]
My onSave callback needs to verify against a state value that changes often. But if I put that state value as a dependency to the useCallback, it will create a new callback each time that state value changes and then useAutosave will call onSave. I would like to silently update onSave without triggering useAutosave to call it.

**Comment by jollyjerr** [comment]
Hi! Sounds good - that behavior would probably make more sense as the default anyway. I'll update asap - but PR's are always welcome in the meantime!
