### ISSUE TITLE
Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by abhi15999** [jollyjerr/react-autosave#26]
Versions:
**react-autosave**: 0.4.2
**react**: 16.8.6

While using the hook **useAutosave** , the following error is being shown. Is the latest release of react-autosave not supported for react 16 ?

![image](https://user-images.githubusercontent.com/56247721/226830731-9e534d12-f245-4935-ad87-f27220b52f96.png)

**Comment by jollyjerr** [comment]
Hi, sorry to be so slow to respond. It looks like you were using commonJS here, which this library no longer supports. I'd recommend using node 16 or later for your project and it should work. I might be wrong though, so if you have any other problems feel free to reopen the issue - thanks!
