### ISSUE TITLE
(node:6111) [DEP0128] DeprecationWarning: Invalid 'main' field in '~/docs-autosync/node_modules/react-autosave/package.json' of 'build/index.js'. Please either fix that or report it to the module author (Use `node --trace-deprecation ...` to show where the warning was created)

### ISSUE THREAD

**Issue by deadcoder0904** [jollyjerr/react-autosave#9]
hey, i get a warning when in my console that says:

> (node:6111) [DEP0128] DeprecationWarning: Invalid 'main' field in '~/docs-autosync/node_modules/react-autosave/package.json' of 'build/index.js'. Please either fix that or report it to the module author (Use `node --trace-deprecation ...` to show where the warning was created)

might wanna fix that :)

**Comment by jollyjerr** [comment]
Thank you for letting me know 👍🏼 . Should be fixed in [0.3.1](https://github.com/jollyjerr/react-autosave/releases/tag/0.3.1)
